.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:OSVVM-github| image:: https://img.shields.io/badge/pyEDAA-OSVVM-ab47bc.svg?longCache=true&style=flat-square&logo=github&longCache=true&logo=GitHub&labelColor=6a1b9a
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM
.. |SHIELD:png:OSVVM-github| image:: https://raster.shields.io/badge/pyEDAA-OSVVM-ab47bc.svg?longCache=true&style=flat-square&logo=github&longCache=true&logo=GitHub&labelColor=6a1b9a
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM

.. # Sourcecode license
.. |SHIELD:svg:OSVVM-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:OSVVM-src-license| image:: https://img.shields.io/pypi/l/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Apache&label=code
   :alt: Code license
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:OSVVM-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/tags
.. |SHIELD:png:OSVVM-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/tags

.. # GitHub release date
.. |SHIELD:svg:OSVVM-date| image:: https://img.shields.io/github/release-date/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/releases
.. |SHIELD:png:OSVVM-date| image:: https://raster.shields.io/github/release-date/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:OSVVM-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/network/dependents
.. |SHIELD:png:OSVVM-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:OSVVM-gha-test| image:: https://img.shields.io/github/actions/workflow/status/edaa-org/pyEDAA.OSVVM/Pipeline.yml?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/actions/workflows/Pipeline.yml
.. |SHIELD:png:OSVVM-gha-test| image:: https://raster.shields.io/github/actions/workflow/status/edaa-org/pyEDAA.OSVVM/Pipeline.yml?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/actions/workflows/Pipeline.yml

.. # Codacy - quality
.. |SHIELD:svg:OSVVM-codacy-quality| image:: https://img.shields.io/codacy/grade/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.OSVVM
.. |SHIELD:png:OSVVM-codacy-quality| image:: https://raster.shields.io/codacy/grade/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.OSVVM

.. # Codacy - coverage
.. |SHIELD:svg:OSVVM-codacy-coverage| image:: https://img.shields.io/codacy/coverage/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.OSVVM
.. |SHIELD:png:OSVVM-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/c2635df20fa840bc85639ca2fa1d9cb4?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pyEDAA.OSVVM

.. # Codecov - coverage
.. |SHIELD:svg:OSVVM-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.OSVVM
.. |SHIELD:png:OSVVM-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pyEDAA.OSVVM

.. # Libraries - source rank
.. |SHIELD:svg:OSVVM-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.OSVVM/sourcerank
.. |SHIELD:png:OSVVM-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.OSVVM/sourcerank

.. # PyPI tag
.. |SHIELD:svg:OSVVM-pypi-tag| image:: https://img.shields.io/pypi/v/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.OSVVM/
.. |SHIELD:png:OSVVM-pypi-tag| image:: https://raster.shields.io/pypi/v/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pyEDAA.OSVVM/

.. # PyPI project status
.. |SHIELD:svg:OSVVM-pypi-status| image:: https://img.shields.io/pypi/status/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:OSVVM-pypi-status| image:: https://raster.shields.io/pypi/status/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:OSVVM-pypi-python| image:: https://img.shields.io/pypi/pyversions/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:OSVVM-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:OSVVM-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.OSVVM
.. |SHIELD:png:OSVVM-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pyEDAA.OSVVM?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pyEDAA.OSVVM

.. # Requires - status
.. |SHIELD:svg:OSVVM-req-status| image:: https://img.shields.io/requires/github/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.OSVVM/requirements/?branch=main
.. |SHIELD:png:OSVVM-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pyEDAA.OSVVM?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pyEDAA.OSVVM/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:OSVVM-doc-license| image:: https://img.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: License.html
.. |SHIELD:png:OSVVM-doc-license| image:: https://raster.shields.io/badge/doc-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://GitHub.com/edaa-org/pyEDAA.OSVVM/blob/main/doc/License.rst

.. # GHPages - read now
.. |SHIELD:svg:OSVVM-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.OSVVM&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.OSVVM%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.OSVVM/
.. |SHIELD:png:OSVVM-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpyEDAA.OSVVM&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpyEDAA.OSVVM%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pyEDAA.OSVVM/

.. # Gitter
.. |SHIELD:svg:OSVVM-gitter| image:: https://img.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
.. |SHIELD:png:OSVVM-gitter| image:: https://raster.shields.io/badge/chat-on%20gitter-4db797.svg?longCache=true&style=flat-square&logo=gitter&logoColor=e8ecef
   :alt: Documentation License
   :height: 22
   :target: https://gitter.im/hdl/community
