# ==================================================================================================================== #
#              _____ ____    _        _      ___  ______     ____     ____  __                                         #
#  _ __  _   _| ____|  _ \  / \      / \    / _ \/ ___\ \   / /\ \   / /  \/  |                                        #
# | '_ \| | | |  _| | | | |/ _ \    / _ \  | | | \___ \\ \ / /  \ \ / /| |\/| |                                        #
# | |_) | |_| | |___| |_| / ___ \  / ___ \ | |_| |___) |\ V /    \ V / | |  | |                                        #
# | .__/ \__, |_____|____/_/   \_\/_/   \_(_)___/|____/  \_/      \_/  |_|  |_|                                        #
# |_|    |___/                                                                                                         #
# ==================================================================================================================== #
# Authors:                                                                                                             #
#   Patrick Lehmann                                                                                                    #
#                                                                                                                      #
# License:                                                                                                             #
# ==================================================================================================================== #
# Copyright 2021-2025 Electronic Design Automation Abstraction (EDA²)                                                  #
#                                                                                                                      #
# Licensed under the Apache License, Version 2.0 (the "License");                                                      #
# you may not use this file except in compliance with the License.                                                     #
# You may obtain a copy of the License at                                                                              #
#                                                                                                                      #
#   http://www.apache.org/licenses/LICENSE-2.0                                                                         #
#                                                                                                                      #
# Unless required by applicable law or agreed to in writing, software                                                  #
# distributed under the License is distributed on an "AS IS" BASIS,                                                    #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                             #
# See the License for the specific language governing permissions and                                                  #
# limitations under the License.                                                                                       #
#                                                                                                                      #
# SPDX-License-Identifier: Apache-2.0                                                                                  #
# ==================================================================================================================== #
#
"""Testcase for unit testing report files generated by OSVVM."""
from datetime     import timedelta
from pathlib      import Path
from unittest     import TestCase

from pyEDAA.Reports.Unittesting.JUnit import Document as JUnitDocument

from pyEDAA.OSVVM.Build               import BuildSummaryDocument
from pyEDAA.OSVVM.AlertLog            import Document as AlertLogDocument, AlertLogException

if __name__ == "__main__": # pragma: no cover
	print("ERROR: you called a testcase declaration file as an executable module.")
	print("Use: 'python -m unitest <testcase module>'")
	exit(1)


class JUnitGeneratedByOSVVM(TestCase):
	def test_OsvvmLibraries(self):
		print()

		junitExampleFile = Path("tests/data/JUnit/OSVVMLibraries_OsvvmLibraries.xml")
		doc = JUnitDocument(junitExampleFile, analyzeAndConvert=True)

		self.assertEqual(0, doc.TestsuiteCount)
		self.assertEqual(0, doc.TestcaseCount)

		print(f"JUnit file:")
		print(f"  Testsuites: {doc.TestsuiteCount}")
		print(f"  Testcases:  {doc.TestcaseCount}")

		print()
		print(f"Statistics:")
		print(f"  Times: parsing by lxml: {doc.AnalysisDuration.total_seconds():.3f}s   convert: {doc.ModelConversionDuration.total_seconds():.3f}s")

	def test_RunAllTests(self):
		print()

		junitExampleFile = Path("tests/data/JUnit/OSVVMLibraries_RunAllTests.xml")
		doc = JUnitDocument(junitExampleFile, analyzeAndConvert=True)

		self.assertGreaterEqual(doc.TestsuiteCount, 15)
		self.assertGreaterEqual(doc.TestcaseCount, 290)

		print("=" * 40)
		tree = doc.ToTree()
		print(tree.Render(), end="")
		print("=" * 40)

		print()
		print(f"JUnit file:")
		print(f"  Testsuites: {doc.TestsuiteCount}")
		print(f"  Testcases:  {doc.TestcaseCount}")

		print()
		print(f"Statistics:")
		print(f"  Times: parsing by lxml: {doc.AnalysisDuration.total_seconds():.3f}s   convert: {doc.ModelConversionDuration.total_seconds():.3f}s")


class YAMLGeneratedByOSVVM(TestCase):
	def test_OsvvmLibraries(self) -> None:
		print()

		yamlPath = Path("tests/data/OSVVM/OSVVMLibraries_OsvvmLibraries.yml")
		doc = BuildSummaryDocument(yamlPath, analyzeAndConvert=True)

		print("=" * 40)
		tree = doc.ToTree()
		print(tree.Render(), end="")
		print("=" * 40)

		print()
		print(f"YAML file:")
		print(f"  Testsuites: {doc.TestsuiteCount}")
		print(f"  Testcases:  {doc.TestcaseCount}")

		print()
		print(f"Statistics:")
		print(f"  Times: parsing by ruamel.yaml: {doc.AnalysisDuration.total_seconds():.3f}s   convert: {doc.ModelConversionDuration.total_seconds():.3f}s")


		self.assertEqual(1, doc.TestsuiteCount)
		self.assertEqual(0, doc.TestcaseCount)

	def test_RunAllTests(self) -> None:
		print()

		yamlPath = Path("tests/data/OSVVM/OSVVMLibraries_RunAllTests.yml")
		doc = BuildSummaryDocument(yamlPath, analyzeAndConvert=True)

		print("=" * 40)
		tree = doc.ToTree()
		print(tree.Render(), end="")
		print("=" * 40)

		print()
		print(f"YAML file:")
		print(f"  Testsuites: {doc.TestsuiteCount}")
		print(f"  Testcases:  {doc.TestcaseCount}")

		print()
		print(f"Statistics:")
		print(f"  Times: parsing by ruamel.yaml: {doc.AnalysisDuration.total_seconds():.3f}s   convert: {doc.ModelConversionDuration.total_seconds():.3f}s")


		self.assertEqual(15, len(doc.Testsuites))
		self.assertIn("Axi4Lite", doc)
		self.assertIn("Axi4Full", doc)
		self.assertIn("AxiStream", doc)
		self.assertIn("Uart", doc)

		axi4lite = doc["Axi4Lite"]
		self.assertEqual(17, len(axi4lite.Testcases))

		axi4 = doc["Axi4Full"]
		self.assertEqual(74, len(axi4.Testcases))

		axi4stream = doc["AxiStream"]
		self.assertEqual(68, len(axi4stream.Testcases))

		uart = doc["Uart"]
		self.assertEqual(10, len(uart.Testcases))

	# 	for suite in doc:
	# 		self.printTestsuite(suite)
	#
	# def printTestsuite(self, testsuite: Testsuite, indent: int = 0):
	# 	print(f"{'  '*indent}{testsuite.Name}")
	# 	for suite in testsuite._testsuites.values():
	# 		self.printTestsuite(suite, indent + 2)
	# 	for case in testsuite:
	# 		self.printTestcase(case, indent + 2)
	#
	# def printTestcase(self, testcase: Testcase, indent: int = 0):
	# 	print(f"{'  ' * indent}{testcase.Name}")


class AlertLog(TestCase):
	def test_Create(self) -> None:
		print()
		invalidTimedelta = timedelta(seconds=-1.0)

		path = Path("tests/data/OSVVM/TbAxi4_BasicReadWrite_alerts.yml")
		doc = AlertLogDocument(path)

		self.assertEqual(path, doc.Path)
		with self.assertRaises(AlertLogException):
			_ = doc.AnalysisDuration
		with self.assertRaises(AlertLogException):
			_ = doc.ModelConversionDuration


	def test_Create_WithParse(self) -> None:
		print()
		zeroTime = timedelta()

		path = Path("tests/data/OSVVM/TbAxi4_BasicReadWrite_alerts.yml")
		doc = AlertLogDocument(path, analyzeAndConvert=True)

		self.assertEqual(path, doc.Path)
		self.assertGreater(doc.AnalysisDuration, zeroTime)
		self.assertGreater(doc.ModelConversionDuration, zeroTime)

		tree = doc.ToTree()
		print(tree.Render())

		print(f"{doc.Name}: {doc.AlertCountWarnings}/{doc.AlertCountErrors}/{doc.AlertCountFailures}")
		for item in doc:
			print(f"  {item.Name:<19}: {item.AlertCountWarnings}/{item.AlertCountErrors}/{item.AlertCountFailures}")
			for innerItem in item:
				print(f"    {innerItem.Name:<17}: {innerItem.AlertCountWarnings}/{innerItem.AlertCountErrors}/{innerItem.AlertCountFailures}")
		print(f"{'=' * 40}")
		print(f"Total errors: {doc.TotalErrors}")

		print()
		print(f"Statistics:")
		print(f"  Times: YAML parsing: {doc.AnalysisDuration}s   convert: {doc.ModelConversionDuration}s")
